//
//  Music.swift
//  Beatbots
//
//  Created by Pedro Giuliano Farina on 15/07/20.
//  Copyright © 2020 Pedro Giuliano Farina. All rights reserved.
//

import Foundation

public class Music {
    public let speed: TimeInterval = 3.25
    private let lockQueue = DispatchQueue(label: "Music")
    public init(name: String) {
        lanes[.Harmony] = [Note(command: .SwipeUp, at: 2.5), Note(command: .SwipeUp, at: 5), Note(command: .SwipeUp, at: 6), Note(command: .SwipeDown, at: 6.5), Note(command: .Tap, at: 7), Note(command: .SwipeLeft, at: 9), Note(command: .SwipeRight, at: 11), Note(command: .SwipeUp, at: 13.5), Note(command: .SwipeUp, at: 15), Note(command: .SwipeUp, at: 16), Note(command: .SwipeDown, at: 17), Note(command: .Tap, at: 19), Note(command: .SwipeLeft, at: 19.5), Note(command: .SwipeRight, at: 21)]
        lanes[.Melody] = [Note(command: .SwipeDown, at: 3), Note(command: .SwipeUp, at: 4), Note(command: .SwipeUp, at: 7), Note(command: .SwipeDown, at: 8), Note(command: .Tap, at: 10), Note(command: .SwipeLeft, at: 11), Note(command: .SwipeUp, at: 14), Note(command: .SwipeUp, at: 16), Note(command: .SwipeUp, at: 16.5), Note(command: .SwipeDown, at: 17), Note(command: .Tap, at: 19), Note(command: .SwipeLeft, at: 22)]
        lanes[.Rhythm] = [
            Note(command: .Tap, at: 5.8 + speed),
            Note(command: .Tap, at: 8.9 + speed),
            Note(command: .Tap, at: 12.1 + speed),
            Note(command: .Tap, at: 15.2 + speed),
            Note(command: .Tap, at: 18.3 + speed),
            Note(command: .Tap, at: 21.7 + speed),
            Note(command: .Tap, at: 24.8 + speed),
            Note(command: .Tap, at: 27.8 + speed),
            Note(command: .Tap, at: 31 + speed),
            Note(command: .SwipeDown, at: 32 + speed),
            Note(command: .SwipeDown, at: 34 + speed),
            Note(command: .SwipeUp, at: 34.6 + speed),
            Note(command: .SwipeDown, at: 35.15 + speed),
            Note(command: .SwipeDown, at: 37.1 + speed),
            Note(command: .SwipeUp, at: 37.5 + speed),
            Note(command: .SwipeDown, at: 38.3 + speed),
            Note(command: .SwipeDown, at: 40.4 + speed),
            Note(command: .SwipeUp, at: 40.8 + speed),
            Note(command: .SwipeDown, at: 41.5 + speed),
            Note(command: .SwipeDown, at: 43.6 + speed),
            Note(command: .SwipeUp, at: 44 + speed),
            Note(command: .SwipeDown, at: 44.8 + speed),
            Note(command: .SwipeDown, at: 46.8 + speed),
            Note(command: .SwipeUp, at: 47.18 + speed),
            Note(command: .SwipeDown, at: 47.95 + speed),
            Note(command: .SwipeDown, at: 50 + speed),
            Note(command: .SwipeUp, at: 50.3 + speed),
            Note(command: .SwipeDown, at: 51 + speed),
            Note(command: .SwipeDown, at: 53 + speed),
            Note(command: .SwipeUp, at: 53.3 + speed),
            Note(command: .SwipeDown, at: 54 + speed),
            Note(command: .SwipeDown, at: 56.3 + speed),
            Note(command: .SwipeUp, at: 56.6 + speed),
            Note(command: .SwipeDown, at: 57.4 + speed),
            Note(command: .SwipeDown, at: 58.5 + speed),
            Note(command: .SwipeUp, at: 59 + speed),
            Note(command: .SwipeDown, at: 60.7 + speed),
            Note(command: .SwipeDown, at: 61.35 + speed),
            Note(command: .SwipeUp, at: 62 + speed),
            Note(command: .SwipeDown, at: 63.9 + speed),
            Note(command: .SwipeDown, at: 64.4 + speed),
            Note(command: .SwipeDown, at: 65.15 + speed),
            Note(command: .SwipeDown, at: 65.6 + speed),
            Note(command: .SwipeDown, at: 66 + speed),
            Note(command: .SwipeUp, at: 66.4 + speed),
            Note(command: .SwipeDown, at: 67.15 + speed),
            Note(command: .SwipeDown, at: 67.55 + speed),
            Note(command: .SwipeDown, at: 68.35 + speed),
            Note(command: .SwipeDown, at: 68.75 + speed),
            Note(command: .SwipeDown, at: 69.2 + speed),
            Note(command: .SwipeUp, at: 69.6 + speed),
            Note(command: .SwipeDown, at: 70.4 + speed),
            Note(command: .SwipeDown, at: 70.75 + speed),
            Note(command: .SwipeDown, at: 71.55 + speed),
            Note(command: .SwipeDown, at: 72 + speed),
            Note(command: .SwipeDown, at: 72.39 + speed),
            Note(command: .SwipeUp, at: 72.8 + speed),
            Note(command: .SwipeDown, at: 73.6 + speed),
            Note(command: .SwipeDown, at: 74 + speed),
            Note(command: .SwipeDown, at: 74.8 + speed),
            Note(command: .SwipeDown, at: 75.16 + speed),
            Note(command: .SwipeDown, at: 75.6 + speed),
            Note(command: .SwipeUp, at: 76 + speed),
            Note(command: .SwipeDown, at: 76.79 + speed),
            Note(command: .SwipeDown, at: 77.15 + speed),
            Note(command: .SwipeDown, at: 78 + speed),
            Note(command: .SwipeDown, at: 78.4 + speed),
            Note(command: .SwipeDown, at: 78.8 + speed),
            Note(command: .SwipeUp, at: 79.15 + speed),
            Note(command: .SwipeDown, at: 80 + speed),
            Note(command: .SwipeDown, at: 80.4 + speed),
            Note(command: .SwipeDown, at: 81.2 + speed),
            Note(command: .SwipeDown, at: 81.6 + speed),
            Note(command: .SwipeDown, at: 82 + speed),
            Note(command: .SwipeUp, at: 82.4 + speed),
            Note(command: .SwipeDown, at: 83.15 + speed),
            Note(command: .SwipeDown, at: 83.6 + speed),
            Note(command: .SwipeDown, at: 84.4 + speed),
            Note(command: .SwipeDown, at: 84.8 + speed),
            Note(command: .SwipeDown, at: 85.15 + speed),
            Note(command: .SwipeUp, at: 85.6 + speed),
            Note(command: .SwipeDown, at: 86.4 + speed),
            Note(command: .SwipeDown, at: 86.8 + speed),
            Note(command: .SwipeDown, at: 87.6 + speed),
            Note(command: .SwipeDown, at: 88 + speed),
            Note(command: .SwipeDown, at: 87.6 + speed),
            Note(command: .SwipeDown, at: 88.4 + speed),
            Note(command: .SwipeUp, at: 88.8 + speed),
            Note(command: .SwipeUp, at: 92 + speed),
            Note(command: .SwipeLeft, at: 92.4 + speed),
            Note(command: .SwipeRight, at: 92.8 + speed),
            Note(command: .SwipeLeft, at: 94 + speed),
            Note(command: .SwipeDown, at: 94.8 + speed),
            Note(command: .SwipeUp, at: 95.2 + speed),
            Note(command: .SwipeLeft, at: 95.6 + speed),
            Note(command: .SwipeDown, at: 96 + speed),
            Note(command: .SwipeLeft, at: 97.2 + speed),
            Note(command: .SwipeDown, at: 98 + speed),
            Note(command: .SwipeUp, at: 98.4 + speed),
            Note(command: .SwipeLeft, at: 98.8 + speed),
            Note(command: .SwipeDown, at: 99.2 + speed),
            Note(command: .SwipeLeft, at: 100.4 + speed),
            Note(command: .SwipeDown, at: 101.2 + speed),
            Note(command: .SwipeUp, at: 101.6 + speed),
            Note(command: .SwipeLeft, at: 102 + speed),
            Note(command: .SwipeDown, at: 102.4 + speed),
            Note(command: .SwipeLeft, at: 103.6 + speed),
            Note(command: .SwipeDown, at: 104.4 + speed),
            Note(command: .SwipeUp, at: 104.8 + speed),
            Note(command: .SwipeLeft, at: 105.2 + speed),
            Note(command: .SwipeDown, at: 105.6 + speed),
            Note(command: .SwipeLeft, at: 106.8 + speed),
            Note(command: .SwipeDown, at: 107.6 + speed),
            Note(command: .SwipeUp, at: 108 + speed),
            Note(command: .SwipeLeft, at: 108.4 + speed),
            Note(command: .SwipeDown, at: 108.8 + speed),
            Note(command: .SwipeLeft, at: 110 + speed),
            Note(command: .SwipeDown, at: 110.8 + speed),
            Note(command: .SwipeUp, at: 111.2 + speed),
            Note(command: .SwipeLeft, at: 111.6 + speed),
            Note(command: .SwipeDown, at: 112 + speed),
            Note(command: .SwipeLeft, at: 113.2 + speed),
            Note(command: .SwipeDown, at: 114 + speed),
            Note(command: .SwipeUp, at: 114.35 + speed),
            Note(command: .SwipeLeft, at: 114.7 + speed),
            Note(command: .SwipeDown, at: 115.2 + speed),
            Note(command: .SwipeLeft, at: 116.3 + speed),
            Note(command: .SwipeDown, at: 117.1 + speed),
            Note(command: .SwipeUp, at: 117.5 + speed),
            Note(command: .SwipeLeft, at: 117.9 + speed),
            Note(command: .SwipeDown, at: 118.4 + speed),
            Note(command: .SwipeDown, at: 119 + speed),
            Note(command: .SwipeUp, at: 119.6 + speed),
            Note(command: .SwipeDown, at: 121.6 + speed),
            Note(command: .SwipeDown, at: 122.2 + speed),
            Note(command: .SwipeUp, at: 122.8 + speed),
            Note(command: .SwipeDown, at: 137.6 + speed),
            Note(command: .Tap, at: 138.4 + speed),
            Note(command: .SwipeDown, at: 138.9 + speed),
            Note(command: .SwipeDown, at: 139.6 + speed),
            Note(command: .Tap, at: 140 + speed),
            Note(command: .SwipeDown, at: 140.8 + speed),
            Note(command: .Tap, at: 141.6 + speed),
            Note(command: .SwipeDown, at: 142.15 + speed),
            Note(command: .SwipeDown, at: 142.8 + speed),
            Note(command: .Tap, at: 143.2 + speed),
            Note(command: .SwipeDown, at: 144 + speed),
            Note(command: .Tap, at: 144.8 + speed),
            Note(command: .SwipeDown, at: 145.35 + speed),
            Note(command: .SwipeDown, at: 146 + speed),
            Note(command: .Tap, at: 146.4 + speed),
            Note(command: .SwipeDown, at: 147.2 + speed),
            Note(command: .Tap, at: 148 + speed),
            Note(command: .SwipeDown, at: 148.55 + speed),
            Note(command: .SwipeDown, at: 149.2 + speed),
            Note(command: .Tap, at: 149.6 + speed),
            Note(command: .Tap, at: 151.2 + speed),
            Note(command: .SwipeRight, at: 152 + speed),
            Note(command: .SwipeDown, at: 152.4 + speed),
            Note(command: .Tap, at: 152.8 + speed),
            Note(command: .SwipeLeft, at: 153.2 + speed),
            Note(command: .SwipeRight, at: 153.6 + speed),
            Note(command: .SwipeLeft, at: 154.8 + speed),
            Note(command: .SwipeDown, at: 155.2 + speed),
            Note(command: .SwipeLeft, at: 156 + speed),
            Note(command: .SwipeRight, at: 156.8 + speed),
            Note(command: .SwipeDown, at: 157.4 + speed),
            Note(command: .Tap, at: 158 + speed),
            Note(command: .SwipeRight, at: 158.4 + speed),
            Note(command: .Tap, at: 159.2 + speed),
            Note(command: .SwipeRight, at: 160 + speed),
            Note(command: .SwipeDown, at: 160.6 + speed),
            Note(command: .SwipeUp, at: 161.2 + speed),
            Note(command: .SwipeDown, at: 161.6 + speed),
            Note(command: .SwipeUp, at: 162 + speed),
            Note(command: .SwipeLeft, at: 162.4 + speed),
            Note(command: .SwipeUp, at: 162.8 + speed),
            Note(command: .SwipeRight, at: 163.2 + speed),
            Note(command: .SwipeDown, at: 163.9 + speed),
            Note(command: .Tap, at: 164.4 + speed),
            Note(command: .SwipeRight, at: 164.8 + speed),
            Note(command: .SwipeUp, at: 165.6 + speed),
            Note(command: .SwipeLeft, at: 166 + speed),
            Note(command: .SwipeRight, at: 166.4 + speed),
            Note(command: .SwipeDown, at: 167 + speed),
            Note(command: .Tap, at: 167.6 + speed),
            Note(command: .SwipeUp, at: 168.4 + speed),
            Note(command: .SwipeUp, at: 168.8 + speed),
            Note(command: .SwipeRight, at: 169.6 + speed),
            Note(command: .SwipeDown, at: 170.3 + speed),
            Note(command: .Tap, at: 170.8 + speed),
            Note(command: .SwipeRight, at: 171.2 + speed),
            Note(command: .SwipeUp, at: 172 + speed),
            Note(command: .SwipeUp, at: 172.4 + speed),
            Note(command: .SwipeRight, at: 172.8 + speed),
            Note(command: .Tap, at: 174 + speed),
            Note(command: .SwipeRight, at: 174.4 + speed),
            Note(command: .SwipeDown, at: 175 + speed),
            Note(command: .SwipeLeft, at: 175.55 + speed),
            Note(command: .SwipeRight, at: 176 + speed),
            Note(command: .SwipeDown, at: 176.6 + speed),
            Note(command: .Tap, at: 177.2 + speed),
            Note(command: .SwipeRight, at: 177.6 + speed),
            Note(command: .SwipeUp, at: 178.3 + speed),
            Note(command: .SwipeUp, at: 178.8 + speed),
            Note(command: .SwipeUp, at: 179.2 + speed),
            Note(command: .SwipeRight, at: 192 + speed)
        ]
    }
    private var lanes: [MusicPart: [Note]] = [:]
    public func getNextNoteFor(_ lane: MusicPart) -> Note? {
        guard var notes = lanes[lane], !notes.isEmpty else {
            return nil
        }
        defer {
            lockQueue.sync {
                lanes[lane] = notes
            }
        }
        return notes.removeFirst()
    }
}

public struct Note {
    var command: Command
    var at: TimeInterval
}
