//
//  Music.swift
//  Beatbots
//
//  Created by Pedro Giuliano Farina on 15/07/20.
//  Copyright © 2020 Pedro Giuliano Farina. All rights reserved.
//

import Foundation

public class Music {
    public let speed: TimeInterval = 3.25
    private let lockQueue = DispatchQueue(label: "Music")
    public init(name: String) {
        lanes = [[], [], []]
        lanes[MusicPart.Harmony.getIndex()] = [
            Note(command: .Tap, at: 0 + speed),
            Note(command: .Tap, at: 0.6 + speed),
            Note(command: .SwipeUp, at: 1.2 + speed),
            Note(command: .SwipeUp, at: 3.2 + speed),
            Note(command: .SwipeUp, at: 3.8 + speed),
            Note(command: .Tap, at: 4.4 + speed),
            Note(command: .Tap, at: 6.4 + speed),
            Note(command: .Tap, at: 7 + speed),
            Note(command: .SwipeUp, at: 7.6 + speed),
            Note(command: .SwipeUp, at: 9.6 + speed),
            Note(command: .SwipeUp, at: 10.2 + speed),
            Note(command: .Tap, at: 10.8 + speed),
            Note(command: .Tap, at: 12.8 + speed),
            Note(command: .Tap, at: 13.4 + speed),
            Note(command: .SwipeUp, at: 14 + speed),
            Note(command: .SwipeUp, at: 16 + speed),
            Note(command: .SwipeUp, at: 16.6 + speed),
            Note(command: .Tap, at: 17.2 + speed),
            Note(command: .Tap, at: 19.2 + speed),
            Note(command: .Tap, at: 19.8 + speed),
            Note(command: .SwipeUp, at: 20.4 + speed),
            Note(command: .SwipeUp, at: 22.4 + speed),
            Note(command: .SwipeUp, at: 23 + speed),
            Note(command: .Tap, at: 23.6 + speed),
            Note(command: .Tap, at: 25.6 + speed),
            Note(command: .Tap, at: 26.2 + speed),
            Note(command: .SwipeUp, at: 26.8 + speed),
            Note(command: .SwipeUp, at: 28.6 + speed),
            Note(command: .SwipeUp, at: 29.4 + speed),
            Note(command: .Tap, at: 30 + speed),
            Note(command: .SwipeRight, at: 31.2 + speed),
            Note(command: .SwipeLeft, at: 31.6 + speed),
            Note(command: .Tap, at: 32 + speed),
            Note(command: .Tap, at: 32.6 + speed),
            Note(command: .SwipeUp, at: 33.2 + speed),
            Note(command: .SwipeRight, at: 34.4 + speed),
            Note(command: .SwipeLeft, at: 34.8 + speed),
            Note(command: .SwipeUp, at: 35.2 + speed),
            Note(command: .SwipeUp, at: 35.8 + speed),
            Note(command: .Tap, at: 36.4 + speed),
            Note(command: .SwipeRight, at: 37.6 + speed),
            Note(command: .SwipeLeft, at: 38 + speed),
            Note(command: .Tap, at: 38.4 + speed),
            Note(command: .Tap, at: 39 + speed),
            Note(command: .SwipeUp, at: 39.6 + speed),
            Note(command: .SwipeRight, at: 40.8 + speed),
            Note(command: .SwipeLeft, at: 41.2 + speed),
            Note(command: .SwipeUp, at: 41.6 + speed),
            Note(command: .SwipeUp, at: 42.2 + speed),
            Note(command: .Tap, at: 42.8 + speed),
            Note(command: .SwipeRight, at: 44 + speed),
            Note(command: .SwipeLeft, at: 44.4 + speed),
            Note(command: .Tap, at: 44.8 + speed),
            Note(command: .Tap, at: 45.4 + speed),
            Note(command: .SwipeUp, at: 46 + speed),
            Note(command: .SwipeRight, at: 47.2 + speed),
            Note(command: .SwipeLeft, at: 47.6 + speed),
            Note(command: .SwipeUp, at: 48 + speed),
            Note(command: .SwipeUp, at: 48.6 + speed),
            Note(command: .Tap, at: 49.2 + speed),
            Note(command: .SwipeRight, at: 50.4 + speed),
            Note(command: .SwipeLeft, at: 50.8 + speed),
            Note(command: .Tap, at: 51.2 + speed),
            Note(command: .Tap, at: 51.8 + speed),
            Note(command: .SwipeUp, at: 52.4 + speed),
            Note(command: .SwipeRight, at: 53.6 + speed),
            Note(command: .SwipeLeft, at: 54 + speed),
            Note(command: .SwipeUp, at: 54.4 + speed),
            Note(command: .SwipeUp, at: 55 + speed),
            Note(command: .Tap, at: 55.6 + speed),
            Note(command: .SwipeRight, at: 56.8 + speed),
            Note(command: .SwipeLeft, at: 57.2 + speed),
            Note(command: .Tap, at: 57.6 + speed),
            Note(command: .Tap, at: 58.2 + speed),
            Note(command: .SwipeUp, at: 58.8 + speed),
            Note(command: .SwipeRight, at: 60 + speed),
            Note(command: .SwipeLeft, at: 60.4 + speed),
            Note(command: .SwipeUp, at: 60.8 + speed),
            Note(command: .SwipeUp, at: 61.4 + speed),
            Note(command: .Tap, at: 62 + speed),
            Note(command: .SwipeUp, at: 64.5 + speed),
            Note(command: .SwipeRight, at: 67.5 + speed),
            Note(command: .SwipeUp, at: 70.6 + speed),
            Note(command: .SwipeRight, at: 73.8 + speed),
            Note(command: .SwipeDown, at: 77 + speed),
            Note(command: .SwipeUp, at: 80 + speed),
            Note(command: .SwipeUp, at: 83 + speed),
            Note(command: .SwipeDown, at: 86 + speed),
            Note(command: .SwipeRight, at: 92 + speed),
            Note(command: .SwipeLeft, at: 92.4 + speed),
            Note(command: .Tap, at: 92.8 + speed),
            Note(command: .Tap, at: 93.4 + speed),
            Note(command: .SwipeDown, at: 94 + speed),
            Note(command: .SwipeRight, at: 95.2 + speed),
            Note(command: .SwipeLeft, at: 95.6 + speed),
            Note(command: .SwipeDown, at: 96 + speed),
            Note(command: .SwipeDown, at: 96.6 + speed),
            Note(command: .Tap, at: 97.2 + speed),
            Note(command: .SwipeRight, at: 98.4 + speed),
            Note(command: .SwipeLeft, at: 98.8 + speed),
            Note(command: .Tap, at: 99.2 + speed),
            Note(command: .Tap, at: 99.8 + speed),
            Note(command: .SwipeDown, at: 100.4 + speed),
            Note(command: .SwipeRight, at: 101.6 + speed),
            Note(command: .SwipeLeft, at: 102 + speed),
            Note(command: .SwipeDown, at: 102.4 + speed),
            Note(command: .SwipeDown, at: 103 + speed),
            Note(command: .Tap, at: 103.6 + speed),
            Note(command: .SwipeRight, at: 104.8 + speed),
            Note(command: .SwipeLeft, at: 105.2 + speed),
            Note(command: .Tap, at: 105.6 + speed),
            Note(command: .Tap, at: 106.2 + speed),
            Note(command: .SwipeDown, at: 106.8 + speed),
            Note(command: .SwipeRight, at: 108 + speed),
            Note(command: .SwipeLeft, at: 108.4 + speed),
            Note(command: .SwipeDown, at: 108.8 + speed),
            Note(command: .SwipeDown, at: 109.4 + speed),
            Note(command: .Tap, at: 110 + speed),
            Note(command: .SwipeRight, at: 111.2 + speed),
            Note(command: .SwipeLeft, at: 111.6 + speed),
            Note(command: .Tap, at: 112 + speed),
            Note(command: .Tap, at: 112.6 + speed),
            Note(command: .SwipeDown, at: 113.2 + speed),
            Note(command: .SwipeRight, at: 114.4 + speed),
            Note(command: .SwipeLeft, at: 114.8 + speed),
            Note(command: .SwipeDown, at: 115.2 + speed),
            Note(command: .SwipeDown, at: 115.8 + speed),
            Note(command: .Tap, at: 116.4 + speed),
            Note(command: .SwipeRight, at: 117.6 + speed),
            Note(command: .SwipeLeft, at: 118 + speed),
            Note(command: .Tap, at: 118.4 + speed),
            Note(command: .Tap, at: 119 + speed),
            Note(command: .SwipeDown, at: 119.6 + speed),
            Note(command: .SwipeRight, at: 120.8 + speed),
            Note(command: .SwipeLeft, at: 121.2 + speed),
            Note(command: .SwipeDown, at: 121.6 + speed),
            Note(command: .SwipeDown, at: 122.2 + speed),
            Note(command: .Tap, at: 122.8 + speed),
            Note(command: .SwipeUp, at: 124.8 + speed),
            Note(command: .SwipeDown, at: 125.2 + speed),
            Note(command: .SwipeUp, at: 125.6 + speed),
            Note(command: .SwipeDown, at: 126 + speed),
            Note(command: .SwipeUp, at: 126.4 + speed),
            Note(command: .SwipeDown, at: 126.8 + speed),
            Note(command: .SwipeUp, at: 127.2 + speed),
            Note(command: .SwipeDown, at: 127.6 + speed),
            Note(command: .SwipeRight, at: 128 + speed),
            Note(command: .SwipeLeft, at: 128.4 + speed),
            Note(command: .SwipeRight, at: 128.8 + speed),
            Note(command: .SwipeLeft, at: 129.2 + speed),
            Note(command: .SwipeRight, at: 129.6 + speed),
            Note(command: .SwipeLeft, at: 130 + speed),
            Note(command: .SwipeRight, at: 130.4 + speed),
            Note(command: .SwipeLeft, at: 130.8 + speed),
            Note(command: .SwipeRight, at: 131.2 + speed),
            Note(command: .SwipeLeft, at: 131.6 + speed),
            Note(command: .SwipeDown, at: 132 + speed),
            Note(command: .SwipeUp, at: 132.4 + speed),
            Note(command: .SwipeDown, at: 132.8 + speed),
            Note(command: .SwipeUp, at: 133.2 + speed),
            Note(command: .SwipeDown, at: 133.6 + speed),
            Note(command: .SwipeUp, at: 134 + speed),
            Note(command: .SwipeLeft, at: 134.4 + speed),
            Note(command: .SwipeRight, at: 134.8 + speed),
            Note(command: .SwipeLeft, at: 135.2 + speed),
            Note(command: .SwipeRight, at: 135.6 + speed),
            Note(command: .SwipeLeft, at: 136 + speed),
            Note(command: .SwipeRight, at: 136.4 + speed),
            Note(command: .SwipeLeft, at: 136.8 + speed),
            Note(command: .SwipeDown, at: 137.2 + speed),
            Note(command: .SwipeUp, at: 137.6 + speed),
            Note(command: .SwipeDown, at: 138 + speed),
            Note(command: .SwipeUp, at: 138.4 + speed),
            Note(command: .SwipeDown, at: 138.8 + speed),
            Note(command: .SwipeUp, at: 139.2 + speed),
            Note(command: .SwipeDown, at: 139.6 + speed),
            Note(command: .SwipeUp, at: 140 + speed),
            Note(command: .SwipeDown, at: 140.4 + speed),
            Note(command: .SwipeUp, at: 140.8 + speed),
            Note(command: .SwipeDown, at: 141.2 + speed),
            Note(command: .SwipeUp, at: 141.6 + speed),
            Note(command: .SwipeDown, at: 142 + speed),
            Note(command: .SwipeUp, at: 142.4 + speed),
            Note(command: .SwipeDown, at: 142.8 + speed),
            Note(command: .SwipeUp, at: 143.2 + speed),
            Note(command: .SwipeDown, at: 143.6 + speed),
            Note(command: .SwipeUp, at: 144 + speed),
            Note(command: .SwipeUp, at: 144.4 + speed),
            Note(command: .SwipeUp, at: 144.8 + speed),
            Note(command: .SwipeUp, at: 145.2 + speed),
            Note(command: .SwipeUp, at: 145.6 + speed),
            Note(command: .SwipeUp, at: 146 + speed),
            Note(command: .SwipeUp, at: 146.4 + speed),
            Note(command: .SwipeUp, at: 146.8 + speed),
            Note(command: .SwipeRight, at: 147.2 + speed),
            Note(command: .SwipeLeft, at: 147.6 + speed),
            Note(command: .SwipeRight, at: 148 + speed),
            Note(command: .SwipeLeft, at: 148.4 + speed),
            Note(command: .SwipeRight, at: 148.8 + speed),
            Note(command: .SwipeLeft, at: 149.2 + speed),
            Note(command: .SwipeRight, at: 149.6 + speed),
            Note(command: .SwipeLeft, at: 150 + speed),
            Note(command: .SwipeUp, at: 153.6 + speed),
            Note(command: .SwipeUp, at: 153.6 + speed),
            Note(command: .SwipeRight, at: 157 + speed),
            Note(command: .SwipeUp, at: 158.5 + speed),
            Note(command: .SwipeUp, at: 160 + speed),
            Note(command: .SwipeDown, at: 163.25 + speed),
            Note(command: .SwipeLeft, at: 165 + speed),
            Note(command: .SwipeUp, at: 166.5 + speed),
            Note(command: .SwipeRight, at: 169.75 + speed),
            Note(command: .SwipeLeft, at: 171.5 + speed),
            Note(command: .SwipeLeft, at: 173.5 + speed),
            Note(command: .SwipeUp, at: 176 + speed),
            Note(command: .SwipeUp, at: 177.75 + speed),
            Note(command: .SwipeDown, at: 179.25 + speed),
            Note(command: .SwipeDown, at: 182.5 + speed),
            Note(command: .SwipeRight, at: 184 + speed),
            Note(command: .SwipeRight, at: 185.75 + speed),
            Note(command: .SwipeLeft, at: 188.75 + speed),
            Note(command: .SwipeRight, at: 191 + speed),
            Note(command: .SwipeUp, at: 192 + speed),
            Note(command: .SwipeUp, at: 195 + speed),
            Note(command: .SwipeUp, at: 197 + speed),
            Note(command: .SwipeDown, at: 198.5 + speed)
        ]

        lanes[MusicPart.Melody.getIndex()] = [
            Note(command: .SwipeDown, at: 6+speed),
            Note(command: .SwipeUp, at: 6.4+speed),
            Note(command: .SwipeDown, at: 6.8+speed),
            Note(command: .SwipeUp, at: 7.2+speed),
            Note(command: .SwipeDown, at: 7.6+speed),
            Note(command: .Tap, at: 8+speed),
            Note(command: .Tap, at: 8.4+speed),

            Note(command: .SwipeDown, at: 9.6+speed),
            Note(command: .SwipeDown, at: 10+speed),
            Note(command: .SwipeLeft, at: 10.4+speed),
            Note(command: .SwipeLeft, at: 10.8+speed),
            Note(command: .Tap, at: 11.2+speed),
            Note(command: .Tap, at: 11.6+speed),

            Note(command: .SwipeUp, at: 12.8+speed),
            Note(command: .SwipeUp, at: 13.2+speed),
            Note(command: .SwipeRight, at: 13.6+speed),
            Note(command: .SwipeRight, at: 14+speed),
            Note(command: .Tap, at: 14.4+speed),
            Note(command: .Tap, at: 14.8+speed),

            Note(command: .Tap, at: 16+speed),
            Note(command: .Tap, at: 16.4+speed),
            Note(command: .Tap, at: 16.8+speed),
            Note(command: .Tap, at: 17.2+speed),
            Note(command: .SwipeDown, at: 17.6+speed),

            Note(command: .Tap, at: 19.2+speed),
            Note(command: .Tap, at: 19.6+speed),
            Note(command: .SwipeRight, at: 20+speed),
            Note(command: .SwipeRight, at: 20.4+speed),
            Note(command: .SwipeLeft, at: 20.8+speed),
            Note(command: .SwipeLeft, at: 21.2+speed),

            Note(command: .SwipeRight, at: 22.4+speed),
            Note(command: .SwipeRight, at: 22.8+speed),
            Note(command: .SwipeLeft, at: 23.2+speed),
            Note(command: .SwipeLeft, at: 23.6+speed),
            Note(command: .Tap, at: 24+speed),
            Note(command: .Tap, at: 24.4+speed),

            Note(command: .SwipeUp, at: 25.6+speed),
            Note(command: .SwipeUp, at: 26+speed),
            Note(command: .SwipeDown, at: 26.4+speed),
            Note(command: .SwipeDown, at: 26.8+speed),
            Note(command: .Tap, at: 27.2+speed),
            Note(command: .Tap, at: 27.6+speed),

            Note(command: .Tap, at: 28.8+speed),
            Note(command: .Tap, at: 29.2+speed),
            Note(command: .Tap, at: 29.6+speed),
            Note(command: .Tap, at: 30+speed),
            Note(command: .SwipeDown, at: 30.4+speed),

            Note(command: .SwipeUp, at: 32.2+speed),
            Note(command: .SwipeUp, at: 33+speed),
            Note(command: .SwipeUp, at: 33.5+speed),
            Note(command: .SwipeLeft, at: 34+speed),
            Note(command: .SwipeRight, at: 34.5+speed),
            Note(command: .Tap, at: 35+speed),
            Note(command: .Tap, at: 35.5+speed),
            Note(command: .Tap, at: 36.2+speed),
            Note(command: .SwipeDown, at: 37+speed),

            Note(command: .Tap, at: 38.7+speed),

            Note(command: .SwipeRight, at: 39+speed),
            Note(command: .SwipeLeft, at: 39.5+speed),
            Note(command: .SwipeRight, at: 40+speed),
            Note(command: .SwipeLeft, at: 41.5+speed),

            Note(command: .SwipeRight, at: 42+speed),
            Note(command: .SwipeLeft, at: 42.5+speed),
            Note(command: .SwipeRight, at: 43+speed),
            Note(command: .SwipeLeft, at: 43.5+speed),
            Note(command: .SwipeRight, at: 44+speed),

            //repeat
            Note(command: .SwipeUp, at: 45.2+speed),
            Note(command: .SwipeUp, at: 46+speed),
            Note(command: .SwipeUp, at: 46.5+speed),
            Note(command: .SwipeLeft, at: 47+speed),
            Note(command: .SwipeRight, at: 47.5+speed),
            Note(command: .Tap, at: 48+speed),
            Note(command: .Tap, at: 48.5+speed),
            Note(command: .Tap, at: 49.2+speed),
            Note(command: .SwipeDown, at: 50+speed),

            Note(command: .Tap, at: 51.7+speed),

            Note(command: .SwipeRight, at: 52+speed),
            Note(command: .SwipeLeft, at: 52.5+speed),
            Note(command: .SwipeRight, at: 53+speed),
            Note(command: .SwipeLeft, at: 54.5+speed),

            Note(command: .SwipeRight, at: 55+speed),
            Note(command: .SwipeLeft, at: 55.5+speed),
            Note(command: .SwipeRight, at: 56+speed),
            Note(command: .SwipeLeft, at: 56.5+speed),
            Note(command: .SwipeRight, at: 57+speed),

            //end
            Note(command: .Tap, at: 58.4+speed),

            Note(command: .SwipeDown, at: 63.4+speed),
            Note(command: .SwipeUp, at: 63.8+speed),
            Note(command: .SwipeDown, at: 64.2+speed),
            Note(command: .SwipeUp, at: 64.6+speed),
            Note(command: .SwipeDown, at: 65+speed),
            Note(command: .Tap, at: 65.4+speed),
            Note(command: .Tap, at: 65.8+speed),

            Note(command: .SwipeDown, at: 67+speed),
            Note(command: .SwipeDown, at: 67.4+speed),
            Note(command: .SwipeLeft, at: 67.8+speed),
            Note(command: .SwipeLeft, at: 68.2+speed),
            Note(command: .Tap, at: 68.6+speed),
            Note(command: .Tap, at: 69+speed),

            Note(command: .SwipeUp, at: 70.2+speed),
            Note(command: .SwipeUp, at: 70.6+speed),
            Note(command: .SwipeLeft, at: 71+speed),
            Note(command: .SwipeLeft, at: 71.4+speed),
            Note(command: .Tap, at: 71.8+speed),
            Note(command: .Tap, at: 72.2+speed),

            Note(command: .Tap, at: 73.4+speed),
            Note(command: .Tap, at: 73.8+speed),
            Note(command: .Tap, at: 74.2+speed),
            Note(command: .Tap, at: 74.6+speed),
            Note(command: .SwipeDown, at: 75+speed),

            Note(command: .SwipeLeft, at: 77+speed),
            Note(command: .SwipeLeft, at: 77.4+speed),
            Note(command: .SwipeRight, at: 77.8+speed),
            Note(command: .SwipeRight, at: 78.2+speed),
            Note(command: .SwipeUp, at: 78.6+speed),
            Note(command: .SwipeUp, at: 79+speed),

            Note(command: .SwipeDown, at: 80.2+speed),
            Note(command: .SwipeDown, at: 80.6+speed),
            Note(command: .SwipeUp, at: 81+speed),
            Note(command: .SwipeUp, at: 81.4+speed),
            Note(command: .Tap, at: 81.8+speed),
            Note(command: .Tap, at: 82.2+speed),

            Note(command: .SwipeDown, at: 83.4+speed),
            Note(command: .SwipeDown, at: 83.8+speed),
            Note(command: .SwipeLeft, at: 84.2+speed),
            Note(command: .SwipeLeft, at: 84.6+speed),
            Note(command: .Tap, at: 85+speed),
            Note(command: .Tap, at: 85.4+speed),

            Note(command: .Tap, at: 86.6+speed),
            Note(command: .Tap, at: 87+speed),
            Note(command: .Tap, at: 87.5+speed),
            Note(command: .Tap, at: 87.7+speed),
            Note(command: .SwipeDown, at: 88.2+speed),

            Note(command: .Tap, at: 89.8+speed),
            Note(command: .Tap, at: 90.2+speed),
            Note(command: .Tap, at: 90.6+speed),
            Note(command: .Tap, at: 91+speed),
            Note(command: .Tap, at: 91.4+speed),
            Note(command: .Tap, at: 91.8+speed),

            Note(command: .SwipeUp, at: 92.2+speed),
            Note(command: .SwipeUp, at: 93+speed),
            Note(command: .SwipeUp, at: 93.5+speed),
            Note(command: .SwipeLeft, at: 94+speed),
            Note(command: .SwipeRight, at: 94.5+speed),
            Note(command: .Tap, at: 95+speed),
            Note(command: .Tap, at: 95.5+speed),
            Note(command: .Tap, at: 96.2+speed),
            Note(command: .SwipeDown, at: 97+speed),

            Note(command: .Tap, at: 98.7+speed),

            Note(command: .SwipeRight, at: 99+speed),
            Note(command: .SwipeLeft, at: 99.5+speed),
            Note(command: .SwipeRight, at: 100+speed),
            Note(command: .SwipeLeft, at: 101.5+speed),

            Note(command: .SwipeRight, at: 102+speed),
            Note(command: .SwipeLeft, at: 102.5+speed),
            Note(command: .SwipeRight, at: 103+speed),
            Note(command: .SwipeLeft, at: 103.5+speed),
            Note(command: .SwipeRight, at: 104+speed),

            //repeat
            Note(command: .SwipeUp, at: 105.2+speed),
            Note(command: .SwipeUp, at: 106+speed),
            Note(command: .SwipeUp, at: 106.5+speed),
            Note(command: .SwipeLeft, at: 107+speed),
            Note(command: .SwipeRight, at: 107.5+speed),
            Note(command: .Tap, at: 108+speed),
            Note(command: .Tap, at: 108.5+speed),
            Note(command: .Tap, at: 109.2+speed),
            Note(command: .SwipeDown, at: 110+speed),

            Note(command: .Tap, at: 111.7+speed),

            Note(command: .SwipeRight, at: 112+speed),
            Note(command: .SwipeLeft, at: 112.5+speed),
            Note(command: .SwipeRight, at: 113+speed),
            Note(command: .SwipeLeft, at: 114.5+speed),

            Note(command: .SwipeRight, at: 115+speed),
            Note(command: .SwipeLeft, at: 115.5+speed),
            Note(command: .SwipeRight, at: 116+speed),
            Note(command: .SwipeLeft, at: 116.5+speed),
            Note(command: .SwipeRight, at: 117+speed),

            //end
            Note(command: .Tap, at: 118.4+speed),

            Note(command: .SwipeUp, at: 124.6+speed),
            Note(command: .SwipeDown, at: 125+speed),
            Note(command: .SwipeUp, at: 125.4+speed),
            Note(command: .SwipeDown, at: 125.8+speed),
            Note(command: .SwipeUp, at: 126.2+speed),
            Note(command: .Tap, at: 126.6+speed),
            Note(command: .Tap, at: 127+speed),

            Note(command: .SwipeDown, at: 128.2+speed),
            Note(command: .SwipeDown, at: 128.6+speed),
            Note(command: .SwipeUp, at: 129+speed),
            Note(command: .SwipeUp, at: 129.4+speed),
            Note(command: .Tap, at: 129.8+speed),
            Note(command: .Tap, at: 130.2+speed),

            Note(command: .SwipeRight, at: 131.4+speed),
            Note(command: .SwipeRight, at: 131.8+speed),
            Note(command: .SwipeLeft, at: 132.2+speed),
            Note(command: .SwipeLeft, at: 132.6+speed),
            Note(command: .Tap, at: 133+speed),
            Note(command: .Tap, at: 133.4+speed),

            Note(command: .Tap, at: 134.6+speed),
            Note(command: .Tap, at: 135+speed),
            Note(command: .Tap, at: 135.4+speed),
            Note(command: .Tap, at: 135.8+speed),
            Note(command: .SwipeDown, at: 136.2+speed),

            Note(command: .Tap, at: 137.8+speed),
            Note(command: .Tap, at: 138.2+speed),
            Note(command: .SwipeRight, at: 138.6+speed),
            Note(command: .SwipeRight, at: 139+speed),
            Note(command: .SwipeLeft, at: 139.4+speed),
            Note(command: .SwipeLeft, at: 139.8+speed),

            Note(command: .SwipeUp, at: 141+speed),
            Note(command: .SwipeUp, at: 141.4+speed),
            Note(command: .SwipeDown, at: 141.8+speed),
            Note(command: .SwipeDown, at: 142.2+speed),
            Note(command: .Tap, at: 142.6+speed),
            Note(command: .Tap, at: 143+speed),

            Note(command: .SwipeRight, at: 144.2+speed),
            Note(command: .SwipeRight, at: 144.6+speed),
            Note(command: .SwipeUp, at: 145+speed),
            Note(command: .SwipeUp, at: 145.4+speed),
            Note(command: .SwipeDown, at: 145.8+speed),
            Note(command: .SwipeDown, at: 146.2+speed),

            Note(command: .Tap, at: 147.4+speed),
            Note(command: .Tap, at: 147.8+speed),
            Note(command: .Tap, at: 148.2+speed),
            Note(command: .Tap, at: 148.6+speed),
            Note(command: .SwipeDown, at: 149+speed),

            Note(command: .SwipeRight, at: 150.6+speed),
            Note(command: .SwipeLeft, at: 151+speed),
            Note(command: .SwipeRight, at: 151.4+speed),
            Note(command: .SwipeLeft, at: 151.8+speed),
            Note(command: .SwipeRight, at: 152.2+speed),
            Note(command: .SwipeLeft, at: 152.6+speed),

            //song's end 3.0
            Note(command: .SwipeRight, at: 155.6+speed),
            Note(command: .SwipeLeft, at: 156+speed),
            Note(command: .SwipeRight, at: 156.4+speed),
            Note(command: .SwipeLeft, at: 156.8+speed),
            Note(command: .SwipeRight, at: 157.2+speed),
            Note(command: .SwipeLeft, at: 157.6+speed),
            Note(command: .SwipeRight, at: 158+speed),

            Note(command: .SwipeRight, at: 159.2+speed),
            Note(command: .SwipeRight, at: 159.6+speed),
            Note(command: .Tap, at: 160+speed),
            Note(command: .Tap, at: 160.4+speed),
            Note(command: .SwipeLeft, at: 160.8+speed),
            Note(command: .SwipeLeft, at: 161.2+speed),

            Note(command: .Tap, at: 162.4+speed),
            Note(command: .Tap, at: 162.8+speed),
            Note(command: .SwipeRight, at: 163.2+speed),
            Note(command: .SwipeRight, at: 163.6+speed),
            Note(command: .SwipeUp, at: 164+speed),
            Note(command: .SwipeUp, at: 164.4+speed),

            Note(command: .Tap, at: 165.6+speed),
            Note(command: .Tap, at: 166+speed),
            Note(command: .Tap, at: 166.4+speed),
            Note(command: .Tap, at: 166.8+speed),
            Note(command: .SwipeDown, at: 166.2+speed),

            Note(command: .Tap, at: 168.8+speed),
            Note(command: .Tap, at: 169.2+speed),
            Note(command: .SwipeRight, at: 169.6+speed),
            Note(command: .SwipeRight, at: 170+speed),
            Note(command: .SwipeUp, at: 170.4+speed),
            Note(command: .SwipeUp, at: 170.8+speed),

            Note(command: .SwipeRight, at: 172+speed),
            Note(command: .SwipeRight, at: 172.4+speed),
            Note(command: .SwipeLeft, at: 172.8+speed),
            Note(command: .SwipeLeft, at: 173.2+speed),
            Note(command: .Tap, at: 173.6+speed),
            Note(command: .Tap, at: 174+speed),

            Note(command: .SwipeLeft, at: 175.2+speed),
            Note(command: .SwipeLeft, at: 175.6+speed),
            Note(command: .Tap, at: 176+speed),
            Note(command: .Tap, at: 176.4+speed),
            Note(command: .SwipeRight, at: 176.8+speed),
            Note(command: .SwipeRight, at: 177.2+speed),

            Note(command: .Tap, at: 178.4+speed),
            Note(command: .Tap, at: 178.8+speed),
            Note(command: .Tap, at: 179.2+speed),
            Note(command: .Tap, at: 179.6+speed),
            Note(command: .SwipeUp, at: 180+speed),

            Note(command: .SwipeRight, at: 181.6+speed),
            Note(command: .SwipeLeft, at: 182+speed),
            Note(command: .SwipeRight, at: 182.4+speed),
            Note(command: .SwipeLeft, at: 182.8+speed),
            Note(command: .SwipeRight, at: 183.2+speed),
            Note(command: .SwipeLeft, at: 183.6+speed),

            Note(command: .SwipeUp, at: 184.2+speed),
            Note(command: .SwipeUp, at: 185+speed),
            Note(command: .SwipeUp, at: 185.5+speed),
            Note(command: .SwipeLeft, at: 186+speed),
            Note(command: .SwipeRight, at: 186.5+speed),
            Note(command: .Tap, at: 187+speed),
            Note(command: .Tap, at: 187.5+speed),
            Note(command: .Tap, at: 188.2+speed),
            Note(command: .SwipeDown, at: 189+speed),

            Note(command: .Tap, at: 190.7+speed),

            Note(command: .SwipeRight, at: 191+speed),
            Note(command: .SwipeLeft, at: 191.5+speed),
            Note(command: .SwipeRight, at: 192+speed),
            Note(command: .SwipeLeft, at: 193.5+speed),

            Note(command: .SwipeRight, at: 194+speed),
            Note(command: .SwipeLeft, at: 194.5+speed),
            Note(command: .SwipeRight, at: 195+speed),
            Note(command: .SwipeLeft, at: 195.5+speed),
            Note(command: .SwipeRight, at: 196+speed),

            Note(command: .SwipeUp, at: 197.2+speed),
            Note(command: .SwipeUp, at: 198+speed),
            Note(command: .SwipeUp, at: 198.5+speed),
            Note(command: .SwipeLeft, at: 199+speed),
            Note(command: .SwipeRight, at: 199.5+speed),
            Note(command: .Tap, at: 200+speed),
            Note(command: .Tap, at: 200.5+speed),
            Note(command: .Tap, at: 201.2+speed),
            Note(command: .SwipeDown, at: 202+speed),

            Note(command: .Tap, at: 203.7+speed),

            Note(command: .SwipeRight, at: 204+speed),
            Note(command: .SwipeLeft, at: 204.5+speed),
            Note(command: .SwipeRight, at: 205+speed),
            Note(command: .SwipeLeft, at: 206.5+speed),

            Note(command: .SwipeRight, at: 207+speed),
            Note(command: .SwipeLeft, at: 207.5+speed),
            Note(command: .SwipeRight, at: 208+speed),
            Note(command: .SwipeLeft, at: 208.5+speed),
            Note(command: .SwipeRight, at: 209+speed),

            Note(command: .Tap, at: 210.4+speed)
        ]

        lanes[MusicPart.Rhythm.getIndex()] = [
            Note(command: .Tap, at: 5.8 + speed),
            Note(command: .Tap, at: 8.9 + speed),
            Note(command: .Tap, at: 12.1 + speed),
            Note(command: .Tap, at: 15.2 + speed),
            Note(command: .Tap, at: 18.3 + speed),
            Note(command: .Tap, at: 21.7 + speed),
            Note(command: .Tap, at: 24.8 + speed),
            Note(command: .Tap, at: 27.8 + speed),
            Note(command: .Tap, at: 31 + speed),
            Note(command: .SwipeDown, at: 32 + speed),
            Note(command: .SwipeDown, at: 34 + speed),
            Note(command: .SwipeUp, at: 34.6 + speed),
            Note(command: .SwipeDown, at: 35.15 + speed),
            Note(command: .SwipeDown, at: 37.1 + speed),
            Note(command: .SwipeUp, at: 37.5 + speed),
            Note(command: .SwipeDown, at: 38.3 + speed),
            Note(command: .SwipeDown, at: 40.4 + speed),
            Note(command: .SwipeUp, at: 40.8 + speed),
            Note(command: .SwipeDown, at: 41.5 + speed),
            Note(command: .SwipeDown, at: 43.6 + speed),
            Note(command: .SwipeUp, at: 44 + speed),
            Note(command: .SwipeDown, at: 44.8 + speed),
            Note(command: .SwipeDown, at: 46.8 + speed),
            Note(command: .SwipeUp, at: 47.18 + speed),
            Note(command: .SwipeDown, at: 47.95 + speed),
            Note(command: .SwipeDown, at: 50 + speed),
            Note(command: .SwipeUp, at: 50.3 + speed),
            Note(command: .SwipeDown, at: 51 + speed),
            Note(command: .SwipeDown, at: 53 + speed),
            Note(command: .SwipeUp, at: 53.3 + speed),
            Note(command: .SwipeDown, at: 54 + speed),
            Note(command: .SwipeDown, at: 56.3 + speed),
            Note(command: .SwipeUp, at: 56.6 + speed),
            Note(command: .SwipeDown, at: 57.4 + speed),
            Note(command: .SwipeDown, at: 58.5 + speed),
            Note(command: .SwipeUp, at: 59 + speed),
            Note(command: .SwipeDown, at: 60.7 + speed),
            Note(command: .SwipeDown, at: 61.35 + speed),
            Note(command: .SwipeUp, at: 62 + speed),
            Note(command: .SwipeDown, at: 63.9 + speed),
            Note(command: .SwipeDown, at: 64.4 + speed),
            Note(command: .SwipeDown, at: 65.15 + speed),
            Note(command: .SwipeDown, at: 65.6 + speed),
            Note(command: .SwipeDown, at: 66 + speed),
            Note(command: .SwipeUp, at: 66.4 + speed),
            Note(command: .SwipeDown, at: 67.15 + speed),
            Note(command: .SwipeDown, at: 67.55 + speed),
            Note(command: .SwipeDown, at: 68.35 + speed),
            Note(command: .SwipeDown, at: 68.75 + speed),
            Note(command: .SwipeDown, at: 69.2 + speed),
            Note(command: .SwipeUp, at: 69.6 + speed),
            Note(command: .SwipeDown, at: 70.4 + speed),
            Note(command: .SwipeDown, at: 70.75 + speed),
            Note(command: .SwipeDown, at: 71.55 + speed),
            Note(command: .SwipeDown, at: 72 + speed),
            Note(command: .SwipeDown, at: 72.39 + speed),
            Note(command: .SwipeUp, at: 72.8 + speed),
            Note(command: .SwipeDown, at: 73.6 + speed),
            Note(command: .SwipeDown, at: 74 + speed),
            Note(command: .SwipeDown, at: 74.8 + speed),
            Note(command: .SwipeDown, at: 75.16 + speed),
            Note(command: .SwipeDown, at: 75.6 + speed),
            Note(command: .SwipeUp, at: 76 + speed),
            Note(command: .SwipeDown, at: 76.79 + speed),
            Note(command: .SwipeDown, at: 77.15 + speed),
            Note(command: .SwipeDown, at: 78 + speed),
            Note(command: .SwipeDown, at: 78.4 + speed),
            Note(command: .SwipeDown, at: 78.8 + speed),
            Note(command: .SwipeUp, at: 79.15 + speed),
            Note(command: .SwipeDown, at: 80 + speed),
            Note(command: .SwipeDown, at: 80.4 + speed),
            Note(command: .SwipeDown, at: 81.2 + speed),
            Note(command: .SwipeDown, at: 81.6 + speed),
            Note(command: .SwipeDown, at: 82 + speed),
            Note(command: .SwipeUp, at: 82.4 + speed),
            Note(command: .SwipeDown, at: 83.15 + speed),
            Note(command: .SwipeDown, at: 83.6 + speed),
            Note(command: .SwipeDown, at: 84.4 + speed),
            Note(command: .SwipeDown, at: 84.8 + speed),
            Note(command: .SwipeDown, at: 85.15 + speed),
            Note(command: .SwipeUp, at: 85.6 + speed),
            Note(command: .SwipeDown, at: 86.4 + speed),
            Note(command: .SwipeDown, at: 86.8 + speed),
            Note(command: .SwipeDown, at: 87.6 + speed),
            Note(command: .SwipeDown, at: 88 + speed),
            Note(command: .SwipeDown, at: 87.6 + speed),
            Note(command: .SwipeDown, at: 88.4 + speed),
            Note(command: .SwipeUp, at: 88.8 + speed),
            Note(command: .SwipeUp, at: 92 + speed),
            Note(command: .SwipeLeft, at: 92.4 + speed),
            Note(command: .SwipeRight, at: 92.8 + speed),
            Note(command: .SwipeLeft, at: 94 + speed),
            Note(command: .SwipeDown, at: 94.8 + speed),
            Note(command: .SwipeUp, at: 95.2 + speed),
            Note(command: .SwipeLeft, at: 95.6 + speed),
            Note(command: .SwipeDown, at: 96 + speed),
            Note(command: .SwipeLeft, at: 97.2 + speed),
            Note(command: .SwipeDown, at: 98 + speed),
            Note(command: .SwipeUp, at: 98.4 + speed),
            Note(command: .SwipeLeft, at: 98.8 + speed),
            Note(command: .SwipeDown, at: 99.2 + speed),
            Note(command: .SwipeLeft, at: 100.4 + speed),
            Note(command: .SwipeDown, at: 101.2 + speed),
            Note(command: .SwipeUp, at: 101.6 + speed),
            Note(command: .SwipeLeft, at: 102 + speed),
            Note(command: .SwipeDown, at: 102.4 + speed),
            Note(command: .SwipeLeft, at: 103.6 + speed),
            Note(command: .SwipeDown, at: 104.4 + speed),
            Note(command: .SwipeUp, at: 104.8 + speed),
            Note(command: .SwipeLeft, at: 105.2 + speed),
            Note(command: .SwipeDown, at: 105.6 + speed),
            Note(command: .SwipeLeft, at: 106.8 + speed),
            Note(command: .SwipeDown, at: 107.6 + speed),
            Note(command: .SwipeUp, at: 108 + speed),
            Note(command: .SwipeLeft, at: 108.4 + speed),
            Note(command: .SwipeDown, at: 108.8 + speed),
            Note(command: .SwipeLeft, at: 110 + speed),
            Note(command: .SwipeDown, at: 110.8 + speed),
            Note(command: .SwipeUp, at: 111.2 + speed),
            Note(command: .SwipeLeft, at: 111.6 + speed),
            Note(command: .SwipeDown, at: 112 + speed),
            Note(command: .SwipeLeft, at: 113.2 + speed),
            Note(command: .SwipeDown, at: 114 + speed),
            Note(command: .SwipeUp, at: 114.35 + speed),
            Note(command: .SwipeLeft, at: 114.7 + speed),
            Note(command: .SwipeDown, at: 115.2 + speed),
            Note(command: .SwipeLeft, at: 116.3 + speed),
            Note(command: .SwipeDown, at: 117.1 + speed),
            Note(command: .SwipeUp, at: 117.5 + speed),
            Note(command: .SwipeLeft, at: 117.9 + speed),
            Note(command: .SwipeDown, at: 118.4 + speed),
            Note(command: .SwipeDown, at: 119 + speed),
            Note(command: .SwipeUp, at: 119.6 + speed),
            Note(command: .SwipeDown, at: 121.6 + speed),
            Note(command: .SwipeDown, at: 122.2 + speed),
            Note(command: .SwipeUp, at: 122.8 + speed),
            Note(command: .SwipeDown, at: 137.6 + speed),
            Note(command: .Tap, at: 138.4 + speed),
            Note(command: .SwipeDown, at: 138.9 + speed),
            Note(command: .SwipeDown, at: 139.6 + speed),
            Note(command: .Tap, at: 140 + speed),
            Note(command: .SwipeDown, at: 140.8 + speed),
            Note(command: .Tap, at: 141.6 + speed),
            Note(command: .SwipeDown, at: 142.15 + speed),
            Note(command: .SwipeDown, at: 142.8 + speed),
            Note(command: .Tap, at: 143.2 + speed),
            Note(command: .SwipeDown, at: 144 + speed),
            Note(command: .Tap, at: 144.8 + speed),
            Note(command: .SwipeDown, at: 145.35 + speed),
            Note(command: .SwipeDown, at: 146 + speed),
            Note(command: .Tap, at: 146.4 + speed),
            Note(command: .SwipeDown, at: 147.2 + speed),
            Note(command: .Tap, at: 148 + speed),
            Note(command: .SwipeDown, at: 148.55 + speed),
            Note(command: .SwipeDown, at: 149.2 + speed),
            Note(command: .Tap, at: 149.6 + speed),
            Note(command: .Tap, at: 151.2 + speed),
            Note(command: .SwipeRight, at: 152 + speed),
            Note(command: .SwipeDown, at: 152.4 + speed),
            Note(command: .Tap, at: 152.8 + speed),
            Note(command: .SwipeLeft, at: 153.2 + speed),
            Note(command: .SwipeRight, at: 153.6 + speed),
            Note(command: .SwipeLeft, at: 154.8 + speed),
            Note(command: .SwipeDown, at: 155.2 + speed),
            Note(command: .SwipeLeft, at: 156 + speed),
            Note(command: .SwipeRight, at: 156.8 + speed),
            Note(command: .SwipeDown, at: 157.4 + speed),
            Note(command: .Tap, at: 158 + speed),
            Note(command: .SwipeRight, at: 158.4 + speed),
            Note(command: .Tap, at: 159.2 + speed),
            Note(command: .SwipeRight, at: 160 + speed),
            Note(command: .SwipeDown, at: 160.6 + speed),
            Note(command: .SwipeUp, at: 161.2 + speed),
            Note(command: .SwipeDown, at: 161.6 + speed),
            Note(command: .SwipeUp, at: 162 + speed),
            Note(command: .SwipeLeft, at: 162.4 + speed),
            Note(command: .SwipeUp, at: 162.8 + speed),
            Note(command: .SwipeRight, at: 163.2 + speed),
            Note(command: .SwipeDown, at: 163.9 + speed),
            Note(command: .Tap, at: 164.4 + speed),
            Note(command: .SwipeRight, at: 164.8 + speed),
            Note(command: .SwipeUp, at: 165.6 + speed),
            Note(command: .SwipeLeft, at: 166 + speed),
            Note(command: .SwipeRight, at: 166.4 + speed),
            Note(command: .SwipeDown, at: 167 + speed),
            Note(command: .Tap, at: 167.6 + speed),
            Note(command: .SwipeUp, at: 168.4 + speed),
            Note(command: .SwipeUp, at: 168.8 + speed),
            Note(command: .SwipeRight, at: 169.6 + speed),
            Note(command: .SwipeDown, at: 170.3 + speed),
            Note(command: .Tap, at: 170.8 + speed),
            Note(command: .SwipeRight, at: 171.2 + speed),
            Note(command: .SwipeUp, at: 172 + speed),
            Note(command: .SwipeUp, at: 172.4 + speed),
            Note(command: .SwipeRight, at: 172.8 + speed),
            Note(command: .Tap, at: 174 + speed),
            Note(command: .SwipeRight, at: 174.4 + speed),
            Note(command: .SwipeDown, at: 175 + speed),
            Note(command: .SwipeLeft, at: 175.55 + speed),
            Note(command: .SwipeRight, at: 176 + speed),
            Note(command: .SwipeDown, at: 176.6 + speed),
            Note(command: .Tap, at: 177.2 + speed),
            Note(command: .SwipeRight, at: 177.6 + speed),
            Note(command: .SwipeUp, at: 178.3 + speed),
            Note(command: .SwipeUp, at: 178.8 + speed),
            Note(command: .SwipeUp, at: 179.2 + speed),
            Note(command: .SwipeRight, at: 192 + speed)
        ]

        totalNotes = [0, 0, 0]
        totalNotes[MusicPart.Rhythm.getIndex()] = lanes[MusicPart.Rhythm.getIndex()].count
        totalNotes[MusicPart.Melody.getIndex()] = lanes[MusicPart.Melody.getIndex()].count
        totalNotes[MusicPart.Harmony.getIndex()] = lanes[MusicPart.Harmony.getIndex()].count
    }

    public var totalNotes: [Int] = []
    private var lanes: [[Note]] = []
    public func getNextNoteFor(_ lane: MusicPart) -> Note? {
        var notes = lanes[lane.getIndex()]
        guard !notes.isEmpty else {
            return nil
        }
        defer {
            lockQueue.sync {
                lanes[lane.getIndex()] = notes
            }
        }
        return notes.removeFirst()
    }
}

public struct Note {
    var command: Command
    var at: TimeInterval
}
